---
name: 🐛 Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "triage"]
---

## 🐛 Bug Description

### 📝 Summary
<!-- A clear and concise description of the bug -->

### 🔄 Steps to Reproduce
<!-- Steps to reproduce the behavior -->
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### ✅ Expected Behavior
<!-- What you expected to happen -->

### ❌ Actual Behavior
<!-- What actually happened -->

### 📊 Environment
- **OS**: <!-- e.g. Windows 11, macOS 12.1, Ubuntu 20.04 -->
- **Node.js Version**: <!-- e.g. 18.17.0 -->
- **NestJS Version**: <!-- e.g. 10.0.0 -->
- **Library Version**: <!-- e.g. 1.0.0 -->
- **Package Manager**: <!-- npm, yarn, pnpm -->

### 📋 Additional Context
<!-- Add any other context about the problem here -->

### 📎 Attachments
<!-- If applicable, add screenshots, logs, or other files -->
