name: API Documentation

on:
  push:
    tags: 
      - 'v*'

jobs:
  generate-api-docs:
    runs-on: ubuntu-latest

    permissions: 
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: ^10.15.0

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 20.x
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate API docs
        run: pnpm typedoc

      - name: Commit and push API docs
        uses: stefanzweifel/git-auto-commit-action@v6.0.1
        with:
          commit_message: "chore(docs): update API documentation"
          branch: main
          file_pattern: "docs/api/**/*.md"